version: '3.9'
services:
  api:
    container_name: golang_container
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DBNAME=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    restart: on-failure
    volumes:
      - .:/api
    env_file: .env
    depends_on:
      - postgresdb
    networks:
      - learning

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    ports:
      - '1234:5432'
    restart: always
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge
